Consolidate on google-api 1.2.1 jars and add oauth-client (#6676)
There are spurious build breaks (and possible runtime breaks)
on this class for what appears to be awhile now.

```
                       [error] /export/hdd3/workspace/EXEC_0/build/src/jvm/com/foursquare/external/googledocs/ConcreteGoogleDocs.scala:8:30: object auth is not a member of package com.google.api.client
                       [error] import com.google.api.client.auth.oauth2.TokenResponse
```

That TokenResponse is in the oauth-client library:
```
mateo-2:2 mateo$ unzip -l  ~/.pom2/com/google/oauth-client/google-oauth-client/1.21.0/google-oauth-client-1.21.0.jar | grep TokenResponse
     4561  11-19-2015 14:23   com/google/api/client/auth/openidconnect/IdTokenResponse.class
     3028  11-19-2015 14:23   com/google/api/client/auth/oauth2/TokenResponse.class
     3443  11-19-2015 14:23   com/google/api/client/auth/oauth2/TokenResponseException.class
```

and is in the actual pom for the google-api-client:
  * https://github.com/google/google-api-java-client/blob/1.21.0/google-api-client/pom.xml

More importantly, it is first-class imported by our code without having any
references in 3rdparty/BUILD.
```
package com.foursquare.external.googledocs

import com.foursquare.common.global.Application
import com.foursquare.common.logging.MessageLogging
import com.foursquare.common.scala.DangerousRetry
import com.google.api.client.auth.oauth2.TokenResponse
```

buildgen is also conspiring to keep this a secret from us:
```
 'google': {
      'api': {
        'client': {
          'googleapis': {
            'auth': {
              'oauth2': 'libmirror'
            },
            'batch': {
              'json': 'libmirror'
            },
            'javanet': 'gdata',
            'json': 'libmirror'
          },
          'auth': {
            'oauth2': 'gdata'  # note(stefano): this probably shouldn't be in gdata
          },
          'http': 'libmirror',
          'json': 'libmirror',
          'util': 'gdata'
        },
        'services': {
          'drive': 'gdata',
          'mirror': 'libmirror'
        }
      },
```
(sapling split of 8d320436f7eda1480738920f35e56d7cc244b042)